# autogenerated by txs
#include:\__msg_kernel_new:nnnn{box
#include:graphics}}
\ExplFileDate#S
\ExplFileDescription#S
\ExplFileName#S
\ExplFileVersion#S
\ExplLoaderFileVersion#S
\GetIdInfoLog#S
\ProvidesExplClass{arg1}#S
\ProvidesExplFile{arg1}#S
\ProvidesExplPackage{arg1}#S
\color{arg1}{arg2}#S
\expl#S
\l#S
