# autogenerated by txs
#include:longtable
\FBifLTcapwidth#S
\caption#S
\captionskip#S
\endlasthead#S
\endlongtable#S
\endprelastfoot#S
\floatfont#S
\floatfoot#S
\floatfootskip#S
\flrow#S
\longtable#S
\next#S
\setLTcapwidth{arg1}#S
\theFBLTpage
