# autogenerated by txs
\glsinlinedescformat{arg1}{arg2}{arg3}#S
\glsinlinedopostchild#S
\glsinlineemptydescformat{arg1}{arg2}#S
\glsinlinenameformat{arg1}{arg2}#S
\glsinlineparentchildseparator#S
\glsinlinepostchild#S
\glsinlineseparator#S
\glsinlinesubdescformat{arg1}{arg2}{arg3}#S
\glsinlinesubnameformat{arg1}{arg2}#S
\glsinlinesubseparator#S
\glspostinline#S
