# autogenerated by txs
\csname#S
\glssetwidest[opt]{arg1}#S
\glssetwidest{arg1}#S
\glstreechildpredesc#S
\glstreegroupheaderfmt{arg1}#S
\glstreeitem#S
\glstreenamebox{arg1}{arg2}#S
\glstreenamefmt{arg1}#S
\glstreenavigationfmt{arg1}#S
\glstreepredesc#S
\glstreesubitem#S
\glstreesubsubitem#S
\indexspace#S
\item#S
\subitem#S
\subsubitem#S
