# autogenerated by txs
#include:keyval
\DeclareFloatingEnvironment#S
\ForEachFloatingEnvironment#S
\PrepareListOf{arg1}#S
\SetupFloatingEnvironment{arg1}#S
\addtocontents#S
\addtocontents{arg1}{arg2}#S
\csname#S
\expandafter#S
\ext#S
\listoftoc#S
\newfloat#S
\newfloatsetup#S
\next#S
\noexpand#S
