# autogenerated by txs
#include:inputenc
#include:kvoptions
#include:kvsetkeys
#include:stringenc
\InputenxName#S
\SelectInputDefineMapping{arg1}#S
\SelectInputEncodingList#S
\SelectInputMappings{arg1}#S
\show#S
