# autogenerated by txs
#include:amstext
#include:expl3
#include:graphicx
#include:l3keys2e
#include:textcomp
#include:xparse
#include:xtemplate
\ExplFileDate#S
\ExplFileDescription#S
\ExplFileName#S
\ExplFileVersion#S
